In [1]:
import pandas as pd

In [15]:
forecasts_detail = pd.read_csv("../library/seattle_house/forecasts_detail.csv")
forecasts_detail.shape
forecasts_detail

,model,model_category,split,region_id,lookback_start,forecast_start,forecast_end,mse,mae,rmse,y_true_raw,y_pred_raw
0,timesfm_zero,foundation,train,98223,2016-10-31,2017-10-31,2018-09-30,1.536258e+09,31970.318352,39195.126899,367500.1531|359949.9699|364900.0974|364900.097...,359413.8292|355455.2639|350026.5335|347214.174...
1,timesfm_zero,foundation,train,98026,2020-07-31,2021-07-31,2022-06-30,2.721782e+10,124648.527650,164978.254313,825000.3776|825000.3776|795000.0155|799500.325...,830949.3439|805715.5661|798342.2200|781208.584...
2,timesfm_zero,foundation,train,98106,2020-04-30,2021-04-30,2022-03-31,5.780559e+09,72997.763158,76029.988384,645000.2182|662499.8517|677999.7850|680000.052...,610110.3910|598969.7384|591053.9491|585671.284...
3,timesfm_zero,foundation,train,98146,2019-12-31,2020-12-31,2021-11-30,6.163685e+09,64784.132016,78509.141947,562500.1988|574999.9216|549999.9085|574999.921...,571917.0898|576174.6180|569749.8751|573643.228...
4,timesfm_zero,foundation,train,98055,2017-12-31,2018-12-31,2019-11-30,2.310726e+09,40994.875250,48070.013955,532475.0493|579975.2401|589950.1801|567499.942...,494718.3120|496545.6617|496786.2802|498078.991...
...,...,...,...,...,...,...,...,...,...,...,...,...
23755,stexplainer,spatial_temporal,test,98275,2024-08-31,2025-08-31,2026-07-31,1.740703e+10,112604.332002,131935.713358,1050000.0074|1050000.0074|1034999.6818|988000....,1016061.7774|1011047.0576|1010700.0014|1053073...
23756,stexplainer,spatial_temporal,test,98290,2024-08-31,2025-08-31,2026-07-31,3.233669e+09,45162.915813,56865.361820,839999.7838|819999.8545|799950.3058|799950.305...,830339.3767|819934.1680|824452.9585|841110.022...
23757,stexplainer,spatial_temporal,test,98292,2024-08-31,2025-08-31,2026-07-31,3.740097e+08,16426.145235,19339.331118,662499.8517|673000.1102|688999.9525|690000.100...,681687.5931|639952.7041|671799.0471|666453.464...
23758,stexplainer,spatial_temporal,test,98294,2024-08-31,2025-08-31,2026-07-31,2.385003e+08,12086.573584,15443.453656,563499.9430|568000.2415|574990.0512|569949.865...,562936.4961|556721.4826|567611.9838|572993.130...
23759,stexplainer,spatial_temporal,test,98296,2024-08-31,2025-08-31,2026-07-31,8.289167e+09,64814.670479,91044.861187,1193998.1158|1177499.7292|1200500.5762|1249268...,1064088.6829|1030458.3701|1106636.5466|1037603...

In [27]:
feature_importance = pd.read_csv("../library/seattle_house/feature_importance.csv")
feature_importance.shape
feature_importance

,region_id,lookback_start,forecast_start,group,shap_value,contribution_pct
0,98001,2024-01-31,2025-01-31,median_sale_price,10373.963132,14.788971
1,98001,2024-01-31,2025-01-31,median_days_on_market,-10117.517813,14.423387
2,98001,2024-01-31,2025-01-31,inventory,-9456.615670,13.481214
3,98001,2024-01-31,2025-01-31,active_listings,-7351.582882,10.480310
4,98001,2024-01-31,2025-01-31,median_new_listing_price,-6848.932217,9.763738
...,...,...,...,...,...,...
175,98003,2024-04-30,2025-04-30,inventory,-3909.883591,8.308980
176,98003,2024-04-30,2025-04-30,active_listings,-3839.756488,8.159952
177,98003,2024-04-30,2025-04-30,new_listings,-3373.617270,7.169349
178,98003,2024-04-30,2025-04-30,homes_sold,-1982.583838,4.213233
179,98003,2024-04-30,2025-04-30,median_new_listing_price,-1301.004921,2.764794

In [42]:
# max_importance = feature_importance[feature_importance["contribution_pct"] == feature_importance.groupby("region_id")["contribution_pct"].transform("max")]
feature_importance.groupby("group")["contribution_pct"].max()

group
active_listings               12.690037
average_sale_to_list_ratio    15.842910
homes_sold                    17.891542
inventory                     13.481214
median_days_on_market         29.230558
median_new_listing_price      15.429515
median_sale_price             82.672817
new_listings                  15.157536
pending_sales                 13.897391
Name: contribution_pct, dtype: float64

In [43]:
st_explanation = pd.read_csv("../library/seattle_house/stexplainer_explanation.csv")
st_explanation.shape
st_explanation

,region_id,lookback_start,forecast_start,forecast_end,axis,object_id,importance,contribution_pct
0,98001,2016-03-31,2017-03-31,2018-02-28,node,98002,0.459972,9.987350
1,98001,2016-03-31,2017-03-31,2018-02-28,node,98003,0.460384,9.996282
2,98001,2016-03-31,2017-03-31,2018-02-28,node,98004,0.000000,0.000000
3,98001,2016-03-31,2017-03-31,2018-02-28,node,98005,0.000000,0.000000
4,98001,2016-03-31,2017-03-31,2018-02-28,node,98006,0.000000,0.000000
...,...,...,...,...,...,...,...,...
942475,98296,2024-08-31,2025-08-31,2026-07-31,feature,active_listings,0.800512,11.093778
942476,98296,2024-08-31,2025-08-31,2026-07-31,feature,pending_sales,0.800105,11.088145
942477,98296,2024-08-31,2025-08-31,2026-07-31,feature,inventory,0.802069,11.115363
942478,98296,2024-08-31,2025-08-31,2026-07-31,feature,average_sale_to_list_ratio,0.804068,11.143056
942479,98296,2024-08-31,2025-08-31,2026-07-31,feature,median_new_listing_price,0.802718,11.124345

In [84]:
st_explanation[(st_explanation["region_id"] == 98001) & (st_explanation["forecast_start"] == "2025-03-31") & (st_explanation["axis"] == "feature")].tail(60)

,region_id,lookback_start,forecast_start,forecast_end,axis,object_id,importance,contribution_pct
871904,98001,2024-03-31,2025-03-31,2026-02-28,feature,median_sale_price,0.797625,11.133699
871905,98001,2024-03-31,2025-03-31,2026-02-28,feature,homes_sold,0.793740,11.079474
871906,98001,2024-03-31,2025-03-31,2026-02-28,feature,median_days_on_market,0.798980,11.152622
871907,98001,2024-03-31,2025-03-31,2026-02-28,feature,new_listings,0.793821,11.080602
871908,98001,2024-03-31,2025-03-31,2026-02-28,feature,active_listings,0.793874,11.081342
871909,98001,2024-03-31,2025-03-31,2026-02-28,feature,pending_sales,0.793717,11.079160
871910,98001,2024-03-31,2025-03-31,2026-02-28,feature,inventory,0.795502,11.104077
871911,98001,2024-03-31,2025-03-31,2026-02-28,feature,average_sale_to_list_ratio,0.799121,11.154586
871912,98001,2024-03-31,2025-03-31,2026-02-28,feature,median_new_listing_price,0.797678,11.134439